//created on: Aug 2, 2018
package droolscours

//list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import util.OutputDisplay;

// globals
global OutputDisplay showResult;

rule "Account group1"
    ruleflow-group "Group1"
    when
        Account(  )
    then 
        showResult.showText("Account in Group1");
end


rule "Account group2"
    ruleflow-group "Group2"
    when
        Account(  )
    then 
        showResult.showText("Account in Group2");
end

rule "Start process"
	when
	then
		kcontext.getKieRuntime().startProcess("RF1");
	end
	



