//created on: Jul 31, 2018
package droolscours

//list any import classes here.
import droolscours.Account
import util.OutputDisplay;

//declare any global variables here
global OutputDisplay showResults;



rule "Your First Rule"

    when
        //conditions
        Account()
    then
        //actions
        showResults.showText("The account exists");

end

rule "Your First Rule revisited AccountingPeriod"
    //include attributes such as "salience" here...
    when
        //conditions
        CashFlow()
    then
        //actions
        showResults.showText("The CashFlow exists, inserting an accounting Period");
        AccountingPeriod newPeriod = new AccountingPeriod();
        insert (newPeriod);
end

rule "Rule on AccountingPeriod that are inserting"
	when
		AccountingPeriod()
	then
		showResults.showText("Accounting period exists");
end

	
	
	
	
	
	
	
	
	
	
	
	
	
	