//created on: Jul 31, 2018
package droolscours

//list any import classes here.
import droolscours.Account
import util.OutputDisplay;

//declare any global variables here
global OutputDisplay showResults;



rule "Your First Rule"

    when
        //conditions
        Account()
    then
        //actions
        showResults.showText("The account exists");

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
