//created on: Aug 2, 2018
package course


//list any import classes here.
import course.Order
import course.Product
import course.Trip
import util.OutputDisplay;


//declare any global variables here
global OutputDisplay showResult;


rule "Trip exists"
    when
        Trip()
    then
        //actions
		showResult.showText("Trip exists");
end


rule "Order exists"
    when
        //conditions
        $order : Order( startCity not null && )
    then
        //actions
		showResult.showText("Order exists");
end













